export const attributes = [
  'Arachno',
  'Attack Speed',
  'Combo',
  'Elite',
  'Ignition',
  'Life Recovery',
  'Midas Touch',
  'Undead',
  'Mana Steal',
  'Ender',
  'Blazing',
  'Warrior',
  'Deadeye',
  'Arachno Resistance',
  'Blazing Resistance',
  'Experience',
  'Speed',
  'Undead Resistance',
  'Breeze',
  'Lifeline',
  'Life Regeneration',
  'Mana Pool',
  'Dominance',
  'Ender Resistance',
  'Mana Regeneration',
  'Veteran',
  'Vitality',
  'Fortitude',
  'Magic Find',
  'Blazing Fortune',
  'Fishing Experience',
  'Double Hook',
  'Fisherman',
  'Fishing Speed',
  'Hunter',
  'Trophy Hunter',
  'Infection'
];
