export const items = [
  'Attribute Shard',
  'Aurora Boots',
  'Aurora Chestplate',
  'Aurora Helmet',
  'Aurora Leggings',
  'Berserker Boots',
  'Berserker Chestplate',
  'Berserker Helmet',
  'Berserker Leggings',
  'Blade of the Volcano',
  'Blaze Belt',
  'Burning Aurora Boots',
  'Burning Aurora Chestplate',
  'Burning Aurora Helmet',
  'Burning Aurora Leggings',
  'Burning Crimson Boots',
  'Burning Crimson Chestplate',
  'Burning Crimson Helmet',
  'Burning Crimson Leggings',
  'Burning Terror Boots',
  'Burning Terror Chestplate',
  'Burning Terror Helmet',
  'Burning Terror Leggings',
  'Crimson Boots',
  'Crimson Chestplate',
  'Crimson Helmet',
  'Crimson Leggings',
  'Delirium Necklace',
  'Enrager',
  'Fervor Boots',
  'Fervor Chestplate',
  'Fervor Helmet',
  'Fervor Leggings',
  'Fiery Aurora Boots',
  'Fiery Aurora Chestplate',
  'Fiery Aurora Helmet',
  'Fiery Aurora Leggings',
  'Fiery Crimson Boots',
  'Fiery Crimson Chestplate',
  'Fiery Crimson Helmet',
  'Fiery Crimson Leggings',
  'Fiery Terror Boots',
  'Fiery Terror Chestplate',
  'Fiery Terror Helmet',
  'Fiery Terror Leggings',
  'Fire Freeze Staff',
  'Fire Fury Staff',
  'Fire Veil Wand',
  'Flaming Chestplate',
  'Flaming Fist',
  'Gauntlet of Contagion',
  'Ghast Cloak',
  'Glowstone Gauntlet',
  'Hellfire Rod',
  'Hollow Boots',
  'Hollow Chestplate',
  'Hollow Helmet',
  'Hollow Leggings',
  'Hollow Wand',
  'Hot Aurora Boots',
  'Hot Aurora Chestplate',
  'Hot Aurora Helmet',
  'Hot Aurora Leggings',
  'Hot Crimson Boots',
  'Hot Crimson Chestplate',
  'Hot Crimson Helmet',
  'Hot Crimson Leggings',
  'Hot Hollow Boots',
  'Hot Hollow Chestplate',
  'Hot Hollow Leggings',
  'Hot Terror Boots',
  'Hot Terror Chestplate',
  'Hot Terror Helmet',
  'Hot Terror Leggings',
  'Implosion Belt',
  'Infernal Aurora Boots',
  'Infernal Aurora Chestplate',
  'Infernal Aurora Helmet',
  'Infernal Aurora Leggings',
  'Infernal Crimson Boots',
  'Infernal Crimson Chestplate',
  'Infernal Crimson Helmet',
  'Infernal Crimson Leggings',
  'Infernal Terror Boots',
  'Infernal Terror Chestplate',
  'Infernal Terror Helmet',
  'Infernal Terror Leggings',
  'Inferno Rod',
  'Lava Shell Necklace',
  'Magma Lord Boots',
  'Magma Lord Chestplate',
  'Magma Lord Gauntlet',
  'Magma Lord Helmet',
  'Magma Lord Leggings',
  'Magma Necklace',
  'Magma Rod',
  'Molten Belt',
  'Molten Bracelet',
  'Molten Cloak',
  'Molten Necklace',
  'Moogma Leggings',
  'Ragnarock Axe',
  'Rekindled Ember Boots',
  'Rekindled Ember Chestplate',
  'Rekindled Ember Helmet',
  'Rekindled Ember Leggings',
  'Scourge Cloak',
  'Scoville Belt',
  'Shimmering Hood',
  'Shimmering Slippers',
  'Shimmering Trousers',
  'Shimmering Tunic',
  'Slug Boots',
  'Staff of the Volcano',
  'Strengthened Gauntlet of Contagion',
  'Strengthened Ghast Cloak',
  'Strengthened Glowstone Gauntlet',
  'Strengthened Implosion Belt',
  'Strengthened Molten Belt',
  'Strengthened Molten Bracelet',
  'Strengthened Molten Cloak',
  'Strengthened Molten Necklace',
  'Strengthened Vanquished Blaze Belt',
  'Strengthened Vanquished Ghast Cloak',
  'Strengthened Vanquished Glowstone Gauntlet',
  'Strengthened Vanquished Magma Necklace',
  'Sulphur Bow',
  'Sword of Bad Health',
  'Taurus Helmet',
  'Tera Shell Necklace',
  'Terror Boots',
  'Terror Chestplate',
  'Terror Helmet',
  'Terror Leggings',
  'Thunder Boots',
  'Thunder Chestplate',
  'Thunder Helmet',
  'Thunder Leggings',
  'Thunderbolt Necklace',
  'Undead Fervor Boots',
  'Vanquished Blaze Belt',
  'Vanquished Ghast Cloak',
  'Vanquished Glowstone Gauntlet',
  'Vanquished Magma Necklace',
  'Wand of Strength'
];
